begin_time: 2024-03-01T07:59:55
send_delay: 300
gui: true
burst: false

guide:
  contact_name: 測試名
  nationality: Taiwan
  contact_id: A112439281
  contact_tel: 0900000000
  contact_birth_y: 80
  contact_birth_m: 8
  contact_birth_d: 8
  contact_email: abc@gmail.com
  bank: 銀行
  sub_bank: 某銀行
  bank_account: 0123456789
  bank_name: 帳號名字

custom_data:
  - date: 2024/02/23
    custom_count: 25

  - date: 2024/02/24
    custom_count: 3
